### ISSUE TITLE
Database pool

### ISSUE THREAD

**Issue by vlachouli** [qlack/QLACK-Base-Application#24]
Review and validation of database pool configuration.

**Comment by stephan-sch** [comment]
A proposal for the pooling configuration is following: 

```
    hikari:
      connection-test-query: SELECT 1
      # The property connectionTimeout indicates the maximum number of milliseconds that the service can wait to obtain a connection, defaulting to 30 seconds.
      connection-timeout: 60000
      maximum-pool-size: 30
      # The idleTimeout configuration is the maximum time we will allow a connection to be inactive in the connection pool.
      idle-timeout: 120000
      # The minimumIdle property in Hikari represents the minimum number of inactive connections that the connection pool can maintain. The default number is 10.
      minimum-idle: 10
      # The maxLifetime property of Hikari specifies the time, in milliseconds, that a connection can remain in use after being closed. Be careful not to set a very high time.
      max-lifetime: 300000
```

```
Further properties that may be useful

spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.cacheResultSetMetadata=true
```

**Note**: The above configuration for the cached statements is not compatible with Postgres. In order those properties to have any effect, the underlying datasource in use should support them. E.g. MySQL does supports caching.
